name: Build on macOS
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Build-macOS
        run: |
          brew update
          brew install gh cmake wget automake libtool autoconf
          git clone https://github.com/xmrig/xmrig.git
          mkdir xmrig/build && cd xmrig/scripts
          ./build.hwloc.sh && cd ../build
          cmake .. -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DHWLOC_INCLUDE_DIR=../scripts/deps/include -DHWLOC_LIBRARY=../scripts/deps/lib/libhwloc.a
          make -j$(sysctl -n hw.logicalcpu)
